/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminError = { 'notFound' : null } |
  { 'unauthorized' : null } |
  { 'notPending' : null };
export interface AdminOverview {
  'completedRides' : bigint,
  'totalDrivers' : bigint,
  'feeBalance' : number,
  'pendingVehicles' : bigint,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface DriverView {
  'id' : UserId,
  'completedRides' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'vehicle' : Vehicle,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FareEstimate {
  'total' : number,
  'perKmRate' : number,
  'distanceKm' : number,
  'baseFare' : number,
}
export interface FeeStatementEntry {
  'fee' : number,
  'completedAt' : Timestamp,
  'driverId' : UserId,
  'fare' : number,
  'rideId' : bigint,
  'customerId' : UserId,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface LatLng { 'lat' : number, 'lng' : number }
export type PaymentMethod = { 'card' : null } |
  { 'cash' : null };
export type ProfileError = { 'alreadyExists' : null } |
  { 'notDriver' : null } |
  { 'vehicleRequired' : null } |
  { 'notFound' : null } |
  { 'unauthorized' : null };
export type ProfileRole = { 'customer' : null } |
  { 'driver' : null };
export type Result = { 'ok' : UserProfile } |
  { 'err' : ProfileError };
export type Result_1 = { 'ok' : RideView } |
  { 'err' : RideError };
export type Result_2 = { 'ok' : null } |
  { 'err' : AdminError };
export type Result_3 = { 'ok' : null } |
  { 'err' : RideError };
export type Result_4 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type RideError = { 'profileRequired' : null } |
  { 'driverNotApproved' : null } |
  { 'notAvailable' : null } |
  { 'notCustomer' : null } |
  { 'notDriver' : null } |
  { 'wrongStatus' : null } |
  { 'notFound' : null } |
  { 'unauthorized' : null };
export type RideStatus = { 'in_progress' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'waiting' : null };
export interface RideView {
  'id' : bigint,
  'customerName' : string,
  'status' : RideStatus,
  'completedAt' : [] | [Timestamp],
  'driverId' : [] | [UserId],
  'startedAt' : [] | [Timestamp],
  'paymentMethod' : PaymentMethod,
  'driverVehicle' : [] | [Vehicle],
  'adminFee' : number,
  'fare' : FareEstimate,
  'createdAt' : Timestamp,
  'origin' : LatLng,
  'destinationText' : string,
  'customerId' : UserId,
  'acceptedAt' : [] | [Timestamp],
  'driverName' : [] | [string],
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : ProfileRole,
  'vehicle' : [] | [Vehicle],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface Vehicle {
  'status' : VehicleStatus,
  'model' : string,
  'color' : string,
  'year' : bigint,
  'brand' : string,
  'plate' : string,
}
export interface VehicleInput {
  'model' : string,
  'color' : string,
  'year' : bigint,
  'brand' : string,
  'plate' : string,
}
export type VehicleStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_4>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'acceptRide' : ActorMethod<[bigint], Result_1>,
  'approveVehicle' : ActorMethod<[UserId], Result_2>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeRide' : ActorMethod<[bigint], Result_1>,
  'createProfile' : ActorMethod<
    [ProfileRole, string, [] | [VehicleInput]],
    Result
  >,
  'declineRide' : ActorMethod<[bigint], Result_3>,
  'estimateFare' : ActorMethod<[number, number, string], FareEstimate>,
  'execute' : ActorMethod<[string], Result__1>,
  'getAdminOverview' : ActorMethod<[], AdminOverview>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeeBalance' : ActorMethod<[], number>,
  'getFeeStatement' : ActorMethod<[], Array<FeeStatementEntry>>,
  'getProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getRide' : ActorMethod<[bigint], [] | [RideView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAvailableRides' : ActorMethod<[], Array<RideView>>,
  'listDrivers' : ActorMethod<[], Array<DriverView>>,
  'listMyRides' : ActorMethod<[], Array<RideView>>,
  'listPendingVehicles' : ActorMethod<[], Array<DriverView>>,
  'rejectVehicle' : ActorMethod<[UserId], Result_2>,
  'requestRide' : ActorMethod<
    [number, number, string, PaymentMethod],
    Result_1
  >,
  'schema' : ActorMethod<[], string>,
  'startRide' : ActorMethod<[bigint], Result_1>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateProfile' : ActorMethod<[string], Result>,
  'updateVehicle' : ActorMethod<[VehicleInput], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];