/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const RideStatus = IDL.Variant({
  'in_progress' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'waiting' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const PaymentMethod = IDL.Variant({
  'card' : IDL.Null,
  'cash' : IDL.Null,
});
export const VehicleStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Vehicle = IDL.Record({
  'status' : VehicleStatus,
  'model' : IDL.Text,
  'color' : IDL.Text,
  'year' : IDL.Nat,
  'brand' : IDL.Text,
  'plate' : IDL.Text,
});
export const FareEstimate = IDL.Record({
  'total' : IDL.Float64,
  'perKmRate' : IDL.Float64,
  'distanceKm' : IDL.Float64,
  'baseFare' : IDL.Float64,
});
export const LatLng = IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 });
export const RideView = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : RideStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'driverId' : IDL.Opt(UserId),
  'startedAt' : IDL.Opt(Timestamp),
  'paymentMethod' : PaymentMethod,
  'driverVehicle' : IDL.Opt(Vehicle),
  'adminFee' : IDL.Float64,
  'fare' : FareEstimate,
  'createdAt' : Timestamp,
  'origin' : LatLng,
  'destinationText' : IDL.Text,
  'customerId' : UserId,
  'acceptedAt' : IDL.Opt(Timestamp),
  'driverName' : IDL.Opt(IDL.Text),
});
export const RideError = IDL.Variant({
  'profileRequired' : IDL.Null,
  'driverNotApproved' : IDL.Null,
  'notAvailable' : IDL.Null,
  'notCustomer' : IDL.Null,
  'notDriver' : IDL.Null,
  'wrongStatus' : IDL.Null,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const Result_1 = IDL.Variant({ 'ok' : RideView, 'err' : RideError });
export const AdminError = IDL.Variant({
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
  'notPending' : IDL.Null,
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : AdminError });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProfileRole = IDL.Variant({
  'customer' : IDL.Null,
  'driver' : IDL.Null,
});
export const VehicleInput = IDL.Record({
  'model' : IDL.Text,
  'color' : IDL.Text,
  'year' : IDL.Nat,
  'brand' : IDL.Text,
  'plate' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : ProfileRole,
  'vehicle' : IDL.Opt(Vehicle),
});
export const ProfileError = IDL.Variant({
  'alreadyExists' : IDL.Null,
  'notDriver' : IDL.Null,
  'vehicleRequired' : IDL.Null,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : UserProfile, 'err' : ProfileError });
export const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : RideError });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AdminOverview = IDL.Record({
  'completedRides' : IDL.Nat,
  'totalDrivers' : IDL.Nat,
  'feeBalance' : IDL.Float64,
  'pendingVehicles' : IDL.Nat,
});
export const FeeStatementEntry = IDL.Record({
  'fee' : IDL.Float64,
  'completedAt' : Timestamp,
  'driverId' : UserId,
  'fare' : IDL.Float64,
  'rideId' : IDL.Nat,
  'customerId' : UserId,
});
export const DriverView = IDL.Record({
  'id' : UserId,
  'completedRides' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'vehicle' : Vehicle,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_4], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'acceptRide' : IDL.Func([IDL.Nat], [Result_1], []),
  'approveVehicle' : IDL.Func([UserId], [Result_2], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeRide' : IDL.Func([IDL.Nat], [Result_1], []),
  'createProfile' : IDL.Func(
      [ProfileRole, IDL.Text, IDL.Opt(VehicleInput)],
      [Result],
      [],
    ),
  'declineRide' : IDL.Func([IDL.Nat], [Result_3], []),
  'estimateFare' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Text],
      [FareEstimate],
      [],
    ),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getAdminOverview' : IDL.Func([], [AdminOverview], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeeBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getFeeStatement' : IDL.Func([], [IDL.Vec(FeeStatementEntry)], ['query']),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getRide' : IDL.Func([IDL.Nat], [IDL.Opt(RideView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAvailableRides' : IDL.Func([], [IDL.Vec(RideView)], ['query']),
  'listDrivers' : IDL.Func([], [IDL.Vec(DriverView)], ['query']),
  'listMyRides' : IDL.Func([], [IDL.Vec(RideView)], ['query']),
  'listPendingVehicles' : IDL.Func([], [IDL.Vec(DriverView)], ['query']),
  'rejectVehicle' : IDL.Func([UserId], [Result_2], []),
  'requestRide' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Text, PaymentMethod],
      [Result_1],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'startRide' : IDL.Func([IDL.Nat], [Result_1], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateProfile' : IDL.Func([IDL.Text], [Result], []),
  'updateVehicle' : IDL.Func([VehicleInput], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const RideStatus = IDL.Variant({
    'in_progress' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const PaymentMethod = IDL.Variant({ 'card' : IDL.Null, 'cash' : IDL.Null });
  const VehicleStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Vehicle = IDL.Record({
    'status' : VehicleStatus,
    'model' : IDL.Text,
    'color' : IDL.Text,
    'year' : IDL.Nat,
    'brand' : IDL.Text,
    'plate' : IDL.Text,
  });
  const FareEstimate = IDL.Record({
    'total' : IDL.Float64,
    'perKmRate' : IDL.Float64,
    'distanceKm' : IDL.Float64,
    'baseFare' : IDL.Float64,
  });
  const LatLng = IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 });
  const RideView = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : RideStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'driverId' : IDL.Opt(UserId),
    'startedAt' : IDL.Opt(Timestamp),
    'paymentMethod' : PaymentMethod,
    'driverVehicle' : IDL.Opt(Vehicle),
    'adminFee' : IDL.Float64,
    'fare' : FareEstimate,
    'createdAt' : Timestamp,
    'origin' : LatLng,
    'destinationText' : IDL.Text,
    'customerId' : UserId,
    'acceptedAt' : IDL.Opt(Timestamp),
    'driverName' : IDL.Opt(IDL.Text),
  });
  const RideError = IDL.Variant({
    'profileRequired' : IDL.Null,
    'driverNotApproved' : IDL.Null,
    'notAvailable' : IDL.Null,
    'notCustomer' : IDL.Null,
    'notDriver' : IDL.Null,
    'wrongStatus' : IDL.Null,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : RideView, 'err' : RideError });
  const AdminError = IDL.Variant({
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
    'notPending' : IDL.Null,
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : AdminError });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProfileRole = IDL.Variant({
    'customer' : IDL.Null,
    'driver' : IDL.Null,
  });
  const VehicleInput = IDL.Record({
    'model' : IDL.Text,
    'color' : IDL.Text,
    'year' : IDL.Nat,
    'brand' : IDL.Text,
    'plate' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : ProfileRole,
    'vehicle' : IDL.Opt(Vehicle),
  });
  const ProfileError = IDL.Variant({
    'alreadyExists' : IDL.Null,
    'notDriver' : IDL.Null,
    'vehicleRequired' : IDL.Null,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : UserProfile, 'err' : ProfileError });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : RideError });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AdminOverview = IDL.Record({
    'completedRides' : IDL.Nat,
    'totalDrivers' : IDL.Nat,
    'feeBalance' : IDL.Float64,
    'pendingVehicles' : IDL.Nat,
  });
  const FeeStatementEntry = IDL.Record({
    'fee' : IDL.Float64,
    'completedAt' : Timestamp,
    'driverId' : UserId,
    'fare' : IDL.Float64,
    'rideId' : IDL.Nat,
    'customerId' : UserId,
  });
  const DriverView = IDL.Record({
    'id' : UserId,
    'completedRides' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'vehicle' : Vehicle,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_4], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'acceptRide' : IDL.Func([IDL.Nat], [Result_1], []),
    'approveVehicle' : IDL.Func([UserId], [Result_2], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeRide' : IDL.Func([IDL.Nat], [Result_1], []),
    'createProfile' : IDL.Func(
        [ProfileRole, IDL.Text, IDL.Opt(VehicleInput)],
        [Result],
        [],
      ),
    'declineRide' : IDL.Func([IDL.Nat], [Result_3], []),
    'estimateFare' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Text],
        [FareEstimate],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getAdminOverview' : IDL.Func([], [AdminOverview], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeeBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getFeeStatement' : IDL.Func([], [IDL.Vec(FeeStatementEntry)], ['query']),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getRide' : IDL.Func([IDL.Nat], [IDL.Opt(RideView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAvailableRides' : IDL.Func([], [IDL.Vec(RideView)], ['query']),
    'listDrivers' : IDL.Func([], [IDL.Vec(DriverView)], ['query']),
    'listMyRides' : IDL.Func([], [IDL.Vec(RideView)], ['query']),
    'listPendingVehicles' : IDL.Func([], [IDL.Vec(DriverView)], ['query']),
    'rejectVehicle' : IDL.Func([UserId], [Result_2], []),
    'requestRide' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Text, PaymentMethod],
        [Result_1],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'startRide' : IDL.Func([IDL.Nat], [Result_1], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateProfile' : IDL.Func([IDL.Text], [Result], []),
    'updateVehicle' : IDL.Func([VehicleInput], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };