/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface RideView {
    id: bigint;
    customerName: string;
    status: RideStatus;
    completedAt?: Timestamp;
    driverId?: UserId;
    startedAt?: Timestamp;
    paymentMethod: PaymentMethod;
    driverVehicle?: Vehicle;
    adminFee: number;
    fare: FareEstimate;
    createdAt: Timestamp;
    origin: LatLng;
    destinationText: string;
    customerId: UserId;
    acceptedAt?: Timestamp;
    driverName?: string;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export type Result_2 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: AdminError;
};
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface FeeStatementEntry {
    fee: number;
    completedAt: Timestamp;
    driverId: UserId;
    fare: number;
    rideId: bigint;
    customerId: UserId;
}
export interface Vehicle {
    status: VehicleStatus;
    model: string;
    color: string;
    year: bigint;
    brand: string;
    plate: string;
}
export type Result_1 = {
    __kind__: "ok";
    ok: RideView;
} | {
    __kind__: "err";
    err: RideError;
};
export type Result_4 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface Cell {
    value: Value;
    name: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface VehicleInput {
    model: string;
    color: string;
    year: bigint;
    brand: string;
    plate: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface AdminOverview {
    completedRides: bigint;
    totalDrivers: bigint;
    feeBalance: number;
    pendingVehicles: bigint;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface LatLng {
    lat: number;
    lng: number;
}
export type UserId = Principal;
export type Result = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: ProfileError;
};
export type Result_3 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: RideError;
};
export interface DriverView {
    id: UserId;
    completedRides: bigint;
    name: string;
    createdAt: Timestamp;
    vehicle: Vehicle;
}
export interface FareEstimate {
    total: number;
    perKmRate: number;
    distanceKm: number;
    baseFare: number;
}
export interface UserProfile {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: ProfileRole;
    vehicle?: Vehicle;
}
export enum AdminError {
    notFound = "notFound",
    unauthorized = "unauthorized",
    notPending = "notPending"
}
export enum PaymentMethod {
    card = "card",
    cash = "cash"
}
export enum ProfileError {
    alreadyExists = "alreadyExists",
    notDriver = "notDriver",
    vehicleRequired = "vehicleRequired",
    notFound = "notFound",
    unauthorized = "unauthorized"
}
export enum ProfileRole {
    customer = "customer",
    driver = "driver"
}
export enum RideError {
    profileRequired = "profileRequired",
    driverNotApproved = "driverNotApproved",
    notAvailable = "notAvailable",
    notCustomer = "notCustomer",
    notDriver = "notDriver",
    wrongStatus = "wrongStatus",
    notFound = "notFound",
    unauthorized = "unauthorized"
}
export enum RideStatus {
    in_progress = "in_progress",
    completed = "completed",
    accepted = "accepted",
    waiting = "waiting"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VehicleStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_4>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    acceptRide(rideId: bigint): Promise<Result_1>;
    approveVehicle(driverId: UserId): Promise<Result_2>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeRide(rideId: bigint): Promise<Result_1>;
    createProfile(role: ProfileRole, name: string, vehicle: VehicleInput | null): Promise<Result>;
    declineRide(rideId: bigint): Promise<Result_3>;
    estimateFare(originLat: number, originLng: number, destinationText: string): Promise<FareEstimate>;
    execute(qJson: string): Promise<Result__1>;
    getAdminOverview(): Promise<AdminOverview>;
    getApiDoc(): Promise<string>;
    getCallerProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFeeBalance(): Promise<number>;
    getFeeStatement(): Promise<Array<FeeStatementEntry>>;
    getProfile(userId: UserId): Promise<UserProfile | null>;
    getRide(rideId: bigint): Promise<RideView | null>;
    isCallerAdmin(): Promise<boolean>;
    listAvailableRides(): Promise<Array<RideView>>;
    listDrivers(): Promise<Array<DriverView>>;
    listMyRides(): Promise<Array<RideView>>;
    listPendingVehicles(): Promise<Array<DriverView>>;
    rejectVehicle(driverId: UserId): Promise<Result_2>;
    requestRide(originLat: number, originLng: number, destinationText: string, paymentMethod: PaymentMethod): Promise<Result_1>;
    schema(): Promise<string>;
    startRide(rideId: bigint): Promise<Result_1>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateProfile(name: string): Promise<Result>;
    updateVehicle(vehicle: VehicleInput): Promise<Result>;
}
import type { AdminError as _AdminError, Cell as _Cell, DriverView as _DriverView, Error as _Error, FareEstimate as _FareEstimate, LatLng as _LatLng, PaymentMethod as _PaymentMethod, ProfileError as _ProfileError, ProfileRole as _ProfileRole, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result__1 as _Result__1, RideError as _RideError, RideStatus as _RideStatus, RideView as _RideView, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, Value as _Value, Vehicle as _Vehicle, VehicleInput as _VehicleInput, VehicleStatus as _VehicleStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async acceptRide(arg0: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptRide(arg0);
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptRide(arg0);
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveVehicle(arg0: UserId): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.approveVehicle(arg0);
                return from_candid_Result_2_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveVehicle(arg0);
            return from_candid_Result_2_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeRide(arg0: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.completeRide(arg0);
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeRide(arg0);
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProfile(arg0: ProfileRole, arg1: string, arg2: VehicleInput | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(to_candid_ProfileRole_n29(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(to_candid_ProfileRole_n29(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async declineRide(arg0: bigint): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.declineRide(arg0);
                return from_candid_Result_3_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineRide(arg0);
            return from_candid_Result_3_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async estimateFare(arg0: number, arg1: number, arg2: string): Promise<FareEstimate> {
        if (this.processError) {
            try {
                const result = await this.actor.estimateFare(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.estimateFare(arg0, arg1, arg2);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminOverview(): Promise<AdminOverview> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminOverview();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminOverview();
            return result;
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeeBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeBalance();
            return result;
        }
    }
    async getFeeStatement(): Promise<Array<FeeStatementEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeeStatement();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeeStatement();
            return result;
        }
    }
    async getProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRide(arg0: bigint): Promise<RideView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRide(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRide(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAvailableRides(): Promise<Array<RideView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAvailableRides();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAvailableRides();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDrivers(): Promise<Array<DriverView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDrivers();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDrivers();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyRides(): Promise<Array<RideView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyRides();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyRides();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingVehicles(): Promise<Array<DriverView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingVehicles();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingVehicles();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectVehicle(arg0: UserId): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectVehicle(arg0);
                return from_candid_Result_2_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectVehicle(arg0);
            return from_candid_Result_2_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestRide(arg0: number, arg1: number, arg2: string, arg3: PaymentMethod): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.requestRide(arg0, arg1, arg2, to_candid_PaymentMethod_n58(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestRide(arg0, arg1, arg2, to_candid_PaymentMethod_n58(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async startRide(arg0: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.startRide(arg0);
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startRide(arg0);
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0);
                return from_candid_Result_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0);
            return from_candid_Result_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateVehicle(arg0: VehicleInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVehicle(arg0);
                return from_candid_Result_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVehicle(arg0);
            return from_candid_Result_n32(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdminError_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminError): AdminError {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_DriverView_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DriverView): DriverView {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileError_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileError): ProfileError {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileRole): ProfileRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_RideError_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RideError): RideError {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_RideStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RideStatus): RideStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_RideView_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RideView): RideView {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleStatus): VehicleStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Vehicle_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vehicle): Vehicle {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Vehicle]): Vehicle | null {
    return value.length === 0 ? null : from_candid_Vehicle_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RideView]): RideView | null {
    return value.length === 0 ? null : from_candid_RideView_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _VehicleStatus;
    model: string;
    color: string;
    year: bigint;
    brand: string;
    plate: string;
}): {
    status: VehicleStatus;
    model: string;
    color: string;
    year: bigint;
    brand: string;
    plate: string;
} {
    return {
        status: from_candid_VehicleStatus_n18(_uploadFile, _downloadFile, value.status),
        model: value.model,
        color: value.color,
        year: value.year,
        brand: value.brand,
        plate: value.plate
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _ProfileRole;
    vehicle: [] | [_Vehicle];
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: ProfileRole;
    vehicle?: Vehicle;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_ProfileRole_n36(_uploadFile, _downloadFile, value.role),
        vehicle: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.vehicle))
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n44(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n48(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    completedRides: bigint;
    name: string;
    createdAt: _Timestamp;
    vehicle: _Vehicle;
}): {
    id: UserId;
    completedRides: bigint;
    name: string;
    createdAt: Timestamp;
    vehicle: Vehicle;
} {
    return {
        id: value.id,
        completedRides: value.completedRides,
        name: value.name,
        createdAt: value.createdAt,
        vehicle: from_candid_Vehicle_n16(_uploadFile, _downloadFile, value.vehicle)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _RideStatus;
    completedAt: [] | [_Timestamp];
    driverId: [] | [_UserId];
    startedAt: [] | [_Timestamp];
    paymentMethod: _PaymentMethod;
    driverVehicle: [] | [_Vehicle];
    adminFee: number;
    fare: _FareEstimate;
    createdAt: _Timestamp;
    origin: _LatLng;
    destinationText: string;
    customerId: _UserId;
    acceptedAt: [] | [_Timestamp];
    driverName: [] | [string];
}): {
    id: bigint;
    customerName: string;
    status: RideStatus;
    completedAt?: Timestamp;
    driverId?: UserId;
    startedAt?: Timestamp;
    paymentMethod: PaymentMethod;
    driverVehicle?: Vehicle;
    adminFee: number;
    fare: FareEstimate;
    createdAt: Timestamp;
    origin: LatLng;
    destinationText: string;
    customerId: UserId;
    acceptedAt?: Timestamp;
    driverName?: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_RideStatus_n9(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.completedAt)),
        driverId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.driverId)),
        startedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.startedAt)),
        paymentMethod: from_candid_PaymentMethod_n13(_uploadFile, _downloadFile, value.paymentMethod),
        driverVehicle: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.driverVehicle)),
        adminFee: value.adminFee,
        fare: value.fare,
        createdAt: value.createdAt,
        origin: value.origin,
        destinationText: value.destinationText,
        customerId: value.customerId,
        acceptedAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.acceptedAt)),
        driverName: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.driverName))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    in_progress: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    waiting: null;
}): RideStatus {
    return "in_progress" in value ? RideStatus.in_progress : "completed" in value ? RideStatus.completed : "accepted" in value ? RideStatus.accepted : "waiting" in value ? RideStatus.waiting : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    card: null;
} | {
    cash: null;
}): PaymentMethod {
    return "card" in value ? PaymentMethod.card : "cash" in value ? PaymentMethod.cash : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): VehicleStatus {
    return "pending" in value ? VehicleStatus.pending : "approved" in value ? VehicleStatus.approved : "rejected" in value ? VehicleStatus.rejected : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profileRequired: null;
} | {
    driverNotApproved: null;
} | {
    notAvailable: null;
} | {
    notCustomer: null;
} | {
    notDriver: null;
} | {
    wrongStatus: null;
} | {
    notFound: null;
} | {
    unauthorized: null;
}): RideError {
    return "profileRequired" in value ? RideError.profileRequired : "driverNotApproved" in value ? RideError.driverNotApproved : "notAvailable" in value ? RideError.notAvailable : "notCustomer" in value ? RideError.notCustomer : "notDriver" in value ? RideError.notDriver : "wrongStatus" in value ? RideError.wrongStatus : "notFound" in value ? RideError.notFound : "unauthorized" in value ? RideError.unauthorized : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _AdminError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: AdminError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AdminError_n25(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notFound: null;
} | {
    unauthorized: null;
} | {
    notPending: null;
}): AdminError {
    return "notFound" in value ? AdminError.notFound : "unauthorized" in value ? AdminError.unauthorized : "notPending" in value ? AdminError.notPending : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: _ProfileError;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: ProfileError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n34(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ProfileError_n38(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    driver: null;
}): ProfileRole {
    return "customer" in value ? ProfileRole.customer : "driver" in value ? ProfileRole.driver : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alreadyExists: null;
} | {
    notDriver: null;
} | {
    vehicleRequired: null;
} | {
    notFound: null;
} | {
    unauthorized: null;
}): ProfileError {
    return "alreadyExists" in value ? ProfileError.alreadyExists : "notDriver" in value ? ProfileError.notDriver : "vehicleRequired" in value ? ProfileError.vehicleRequired : "notFound" in value ? ProfileError.notFound : "unauthorized" in value ? ProfileError.unauthorized : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _RideError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: RideError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_RideError_n21(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _RideView;
} | {
    err: _RideError;
}): {
    __kind__: "ok";
    ok: RideView;
} | {
    __kind__: "err";
    err: RideError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_RideView_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_RideError_n21(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RideView>): Array<RideView> {
    return value.map((x)=>from_candid_RideView_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DriverView>): Array<DriverView> {
    return value.map((x)=>from_candid_DriverView_n56(_uploadFile, _downloadFile, x));
}
function to_candid_PaymentMethod_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function to_candid_ProfileRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileRole): _ProfileRole {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleInput | null): [] | [_VehicleInput] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileRole): {
    customer: null;
} | {
    driver: null;
} {
    return value == ProfileRole.customer ? {
        customer: null
    } : value == ProfileRole.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    card: null;
} | {
    cash: null;
} {
    return value == PaymentMethod.card ? {
        card: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
